source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'PromisePay_Example' do
  pod "PromisePay", :path => "../"
end

target 'PromisePay_Tests' do
  pod "PromisePay", :path => "../"
end
